# Generated by Django 4.2.13 on 2024-07-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PPGData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unix_time', models.BigIntegerField()),
                ('ppg_data', models.TextField()),
            ],
        ),
    ]
