# Generated by Django 4.2.13 on 2024-07-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppgdata',
            name='ppg_data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='ppgdata',
            name='unix_time',
            field=models.JSONField(),
        ),
    ]
