# Generated by Django 4.2.13 on 2024-07-04 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_alter_ppgdata_ppg_data_alter_ppgdata_unix_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppgdata',
            old_name='ppg_data',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='ppgdata',
            name='unix_time',
        ),
    ]
